name = "Real number game"
version = "0.1.0"
extra_files = "extras"
intro = "src/game/intro.lean"

[[worlds]]
name = "Sets"
id = 1
levels = [
	"src/game/sets/level01.lean"
        "src/game/sets/level02.lean"
	"src/game/sets/level03.lean"
	"src/game/sets/level04.lean"
]

[[worlds]]
name = "Sup and Inf"
id = 2
levels = [
       	 "src/game/sup_inf/L01defs.lean"]

[[worlds]]
name = "Limits of sequences"
id = 2
parents = [1]
levels = [
	"src/game/limits/L01defs.lean",
]

[[worlds]]
name = "Sums of series"
id = 3
parents = [2]
levels = [
	"src/game/series/L01defs.lean",
]
