name = "Real number game"
version = "0.1.0"
extra_files = "extras"
intro = "src/game/intro.lean"

[[worlds]]
name = "Sup and inf"
id = 1
levels = [
	"src/game/sup_inf/level1.lean",
]

[[worlds]]
name = "Limits of sequences"
id = 2
parents = [1]
levels = [
	"src/game/world2/level1.lean",
]

[[worlds]]
name = "Sums of series"
id = 3
parents = [2]
levels = [
	"src/game/world3/level1.lean",
]
