name = "Real number game"
version = "0.1.0"
extra_files = "extras"
intro = "src/game/intro.lean"

[[worlds]]
name = "Sets"
id = 1
levels = [
	"src/game/sets/L01defs.lean",
    	"src/game/sets/sets_level02.lean",
	"src/game/sets/sets_level03.lean",
	"src/game/sets/sets_level04.lean",
	"src/game/sets/sets_level05.lean",
	"src/game/sets/sets_level06.lean",
	"src/game/sets/sets_level07.lean"
]

[[worlds]]
name = "Sup and Inf"
id = 2
parents = [1]
levels = [
       	 "src/game/sup_inf/level01.lean",
       	 "src/game/sup_inf/level02.lean",
       	 "src/game/sup_inf/level03.lean",
       	 "src/game/sup_inf/level04.lean",
       	 "src/game/sup_inf/supSumSets.lean",
       	 "src/game/sup_inf/infSumSets.lean",
       	 "src/game/sup_inf/supProdConst.lean",
       	 "src/game/sup_inf/supProdSets.lean",
       	 "src/game/sup_inf/lub_rationals.lean"
]

[[worlds]]
name = "Limits of sequences"
id = 3
parents = [2]
levels = [
	"src/game/limits/L01defs.lean",
	"src/game/limits/seq_lim_add.lean",
    	"src/game/limits/seq_limitTimesConst.lean"
]

[[worlds]]
name = "Series"
id = 4
parents = [3]
levels = [
        "src/game/series/tempLevel01.lean",
        "src/game/series/tempLevel02.lean",
        "src/game/series/tempLevel03.lean",
        "src/game/series/tempLevel04.lean",
]

[[worlds]]
name = "Functions"
id = 5
parents = [4]
levels = [
	"src/game/functions/bothInjective.lean",
	"src/game/functions/bothSurjective.lean",
	"src/game/functions/bothBijective.lean", 
	"src/game/functions/twoSidedInverse.lean"
]

[[worlds]]
name = "Integral"
id = 6
parents = [5]
levels = [
	"src/game/integral/tempLevel1.lean"
]

[[worlds]]
name = "Topology of the reals"
id = 7
parents = [6]
levels = [
	"src/game/topology/tempLevel1.lean"
]

