name = "Real number game"
version = "0.1.0"
extra_files = "extras"
intro = "src/game/intro.lean"

[[worlds]]
name = "Sets"
id = 1
levels = [
	"src/game/sets/sets_level01.lean",
    	"src/game/sets/sets_level02.lean",
	"src/game/sets/sets_level03.lean",
	"src/game/sets/sets_level04.lean",
	"src/game/sets/sets_level05.lean",
	"src/game/sets/sets_level06.lean"
]

[[worlds]]
name = "Sup and Inf"
id = 2
parents = [1]
levels = [
       	 "src/game/sup_inf/L01defs.lean"
]

[[worlds]]
name = "Limits of sequences"
id = 3
parents = [2]
levels = [
	"src/game/limits/L01defs.lean",
    	"src/game/limits/seq_limitTimesConst.lean"
]

[[worlds]]
name = "Functions"
id = 4
parents = [3]
levels = [
	"src/game/functions/bothInjective.lean"
]

[[worlds]]
name = "Sums of series"
id = 5
parents = [4]
levels = [
        "src/game/series/L01defs.lean",
]

