name = "Real number game"
version = "0.1.0"
extra_files = "extras"
intro = "src/game/intro.lean"

[[worlds]]
name = "Sets"
id = 1
levels = [
	"src/game/sets/sets_level01.lean",
    "src/game/sets/sets_level02.lean",
	"src/game/sets/sets_level03.lean",
	"src/game/sets/sets_level04.lean",
	"src/game/sets/sets_level05.lean",
	"src/game/sets/sets_level06.lean",
	"src/game/sets/sets_level07.lean",
]
