name = "Real number game"
version = "0.1.0"
extra_files = "extras"
intro = "src/game/intro.lean"

[[worlds]]
name = "Sets"
id = 1
levels = [
	"src/game/sets/sets_level01.lean",
    "src/game/sets/sets_level02.lean",
	"src/game/sets/sets_level03.lean",
	"src/game/sets/sets_level04.lean",
	"src/game/sets/sets_level05.lean",
	"src/game/sets/sets_level06.lean",
	"src/game/sets/sets_level07.lean",
	"src/game/sets/sets_level08.lean",
	"src/game/sets/sets_level09.lean",

]

[[worlds]]
name = "Order"
id = 2
parents = [1]
levels = [
	"src/game/order/level01.lean",
	"src/game/order/level02.lean",
	"src/game/order/level03.lean",
	"src/game/order/level04.lean",
	"src/game/order/level05.lean",
	"src/game/order/level06.lean",
	"src/game/order/level07.lean",
	"src/game/order/level08.lean",
	"src/game/order/level09.lean",
]

[[worlds]]
name = "Max"
id = 3
parents = [1]
levels = [
	"src/game/max/level01.lean",
	"src/game/max/level02.lean",
	"src/game/max/level03.lean",
	"src/game/max/level04.lean",
	"src/game/max/level05.lean",
	"src/game/max/level06.lean",
	"src/game/max/level07.lean",
	"src/game/max/level08.lean",
	"src/game/max/level09.lean",
	"src/game/max/level10.lean",
]

[[worlds]]
name = "Dense Bois"
id = 4
parents = [2, 3]
levels = [
	"src/game/sets/sets_level10.lean",
]

[[worlds]]
name = "Sup and Inf"
id = 5
parents = [4]
levels = [
       	 "src/game/sup_inf/level01.lean",
       	 "src/game/sup_inf/level02.lean",
       	 "src/game/sup_inf/level03.lean",
       	 "src/game/sup_inf/level04.lean",
]

[[worlds]]
name = "Completeness"
id = 6
parents = [5]
levels = [
	"src/game/Completeness/level01.lean",
	"src/game/Completeness/level02.lean",
	"src/game/Completeness/level03.lean",
	"src/game/Completeness/level04.lean",
	"src/game/Completeness/level05.lean",
	"src/game/Completeness/level06.lean",
	"src/game/Completeness/level07.lean",
]

[[worlds]]
name = "Limits"
id = 7
parents = [6]
levels = [
	
	"src/game/limits/Blockus_Time.lean",
	"src/game/Limit_Lemmas/Level01.lean",
	"src/game/Limit_Lemmas/Level02.lean",
	"src/game/Limit_Lemmas/Level03.lean",
	"src/game/Limit_Lemmas/Level04.lean",
	"src/game/Limit_Lemmas/Level05.lean",
	"src/game/limits/Mulv2.lean",
	"src/game/Limit_Lemmas/Level06.lean",
	"src/game/Limit_Lemmas/Level07.lean",
	"src/game/Limit_Lemmas/Level08.lean",
	"src/game/Limit_Lemmas/Level09.lean",
	"src/game/limits/lim_recip.lean",
	"src/game/limits/lim_quo.lean",
	"src/game/Completeness/level085.lean",
	"src/game/Completeness/level09.lean",
	"src/game/Completeness/level10.lean",
]
