name = "Real number game"
version = "0.1.0"
extra_files = "extras"
intro = "src/game/intro.lean"

[[worlds]]
name = "Sets"
id = 1
levels = [
	"src/game/sets/sets_level01.lean",
    "src/game/sets/sets_level02.lean",
	"src/game/sets/sets_level03.lean",
	"src/game/sets/sets_level04.lean",
	"src/game/sets/sets_level05.lean",
	"src/game/sets/sets_level06.lean",
	"src/game/sets/sets_level07.lean",
	"src/game/sets/sets_level08.lean",
	"src/game/sets/sets_level09.lean",

]

[[worlds]]
name = "Order"
id = 2
parents = [1]
levels = [
	"src/game/order/level01.lean",
	"src/game/order/level02.lean",
	"src/game/order/level03.lean",
	"src/game/order/level04.lean",
	"src/game/order/level05.lean",
	"src/game/order/level06.lean",
	"src/game/order/level07.lean",
	"src/game/order/level08.lean",
	"src/game/order/level09.lean",
]

[[worlds]]
name = "Abs"
id = 3
parents = [1]
levels = [
	"src/game/abs/abs_API_test.lean",
]

[[worlds]]
name = "Max"
id = 4
parents = [3]
levels = [
	"src/game/max/level01.lean",
	"src/game/max/level02.lean",
	"src/game/max/level03.lean",
	"src/game/max/level04.lean",
	"src/game/max/level05.lean",
	"src/game/max/level06.lean",
	"src/game/max/level07.lean",
	"src/game/max/level08.lean",
	"src/game/max/level09.lean",
	"src/game/max/level10.lean",
]

[[worlds]]
name = "Dense Bois"
id = 5
parents = [2, 4]
levels = [
	"src/game/sets/sets_level01.lean",
	"src/game/sets/Irrat_Dense_In_Reals.lean",
]

[[worlds]]
name = "Sup and Inf"
id = 6
parents = [5]
levels = [
       	 "src/game/sup_inf/level01.lean",
       	 "src/game/sup_inf/level02.lean",
       	 "src/game/sup_inf/level03.lean",
       	 "src/game/sup_inf/level04.lean",
       	 "src/game/sup_inf/supSumSets.lean",
       	 "src/game/sup_inf/infSumSets.lean",
       	 "src/game/sup_inf/infSumConst.lean",
       	 "src/game/sup_inf/supProdConst.lean",
       	 "src/game/sup_inf/lub_prodSets.lean",
       	 "src/game/sup_inf/supProdSets.lean",
       	 "src/game/sup_inf/lub_rationals.lean",
       	 "src/game/sup_inf/unbdd_iff.lean",
       	 "src/game/sup_inf/rat_complete.lean",
	     "src/game/sup_inf/GLBprop_if_LUBprop.lean",
]

[[worlds]]
name = "Completeness"
id = 7
parents = [6]
levels = [
	"src/game/series/tempLevel01.lean",
    "src/game/series/tempLevel02.lean",
    "src/game/series/tempLevel03.lean",
    "src/game/series/tempLevel04.lean",
	"src/game/Completeness/level01.lean",
	"src/game/Completeness/level02.lean",
	"src/game/Completeness/level03.lean",
	"src/game/Completeness/level04.lean",
	"src/game/Completeness/level05.lean",
	"src/game/Completeness/level06.lean",
	"src/game/Completeness/level07.lean",
	"src/game/Completeness/level08.lean",
]

[[worlds]]
name = "Limit Stuff"
id = 8
parents = [7]
levels = [
	"src/game/limits/Blockus_Time.lean",
]